on:
    push:
      branches: [ master ]
  
jobs:
    deploy:
        name: 'Docker Build and Push to ACR'
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Docker Login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: Build the image and push it to ACR
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/discord-bot:${{ github.sha }}
            file: Dockerfile    
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: url-for-container
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/discord-bot:${{ github.sha }}
            cpu: 1   #Optional
            memory: 0.5   #Optional
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: discord-bot
            location: 'west us'
            secure-environment-variables: DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} HTTP_PROXY=${{ secrets.HTTP_PROXY }} AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} AZURE_COSMOS_URL=${{ secrets.AZURE_COSMOS_URL }} AZURE_BLOB_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}